version: '3.7'

services:
  mysql:
    container_name: mysql_ditto
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ditto
      MYSQL_USER: sandbox_user
      MYSQL_PASSWORD: passpass
    restart: unless-stopped
    volumes:
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'
    ports:
      - '3306:3306'
    networks:
      - dev

  consul:
    image: bitnami/consul:latest
    networks:
      - dev
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'

  consul_init:
    image: consul
    command: |
      sh -c 'set -uex; \
        consul kv import -http-addr=http://consul:8500 @/consul/config/default_config.json'
    volumes:
      - './default_config.json:/consul/config/default_config.json'
    networks:
      - dev
    depends_on:
      - consul
    links:
      - consul:consul

  ditto:
    container_name: ditto
    image: ditto:pre-commit
    restart: unless-stopped
    env_file:
      - env/ditto.env
    environment:
      - PROM_METRIC_NAME_PREFIX=ditto_
      - CONFIG_PROVIDER=consul
      - CONFIG_PATH=ditto
      - CONFIG_ENDPOINT=consul:8500
    command: /bin/server
    ports:
      - "7100:7100"
      - "7101:7101"
      - "7102:7102"
    depends_on:
      - mysql
      - consul_init
    links:
      - mysql:mysql
      - consul:consul
      - consul_init:consul_init
    networks:
      - dev

  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9000:9090
    user: "1000:1000"
    volumes:
      - './docker/prometheus:/etc/prometheus'
      - './docker/_data/prometheus:/prometheus'
    depends_on:
      - ditto
    links:
      - ditto:ditto
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yaml
    networks:
      - dev

networks:
  dev:
    external: true